# Generated by Django 2.1.3 on 2018-12-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbinfo',
            old_name='home_adderess_lat',
            new_name='home_address_lat',
        ),
    ]
