# Generated by Django 2.1.4 on 2018-12-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181216_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbinfo',
            name='gender',
            field=models.IntegerField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100),
        ),
    ]
