# Generated by Django 2.1.4 on 2018-12-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181216_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
    ]
