# Generated by Django 2.1.3 on 2018-12-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_materialtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
