# Generated by Django 2.1.4 on 2018-12-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20181216_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermark',
            old_name='redactor_mark',
            new_name='mark',
        ),
    ]
