# Generated by Django 2.1.4 on 2018-12-17 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20181216_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='average_mark',
            field=models.FloatField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='redactor_mark',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='mark',
            field=models.IntegerField(db_index=True, verbose_name=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
        ),
    ]
